
2014-09-21 14:52:45,576 INFO: errors [in C:\Users\John\Dropbox\independent_work\groupbot\groupbot\__init__.py:40]
2014-09-21 14:52:47,213 INFO: errors [in C:\Users\John\Dropbox\independent_work\groupbot\groupbot\__init__.py:40]
2014-09-21 15:08:26,153 INFO: errors [in C:\Users\John\Dropbox\independent_work\groupbot\groupbot\__init__.py:40]
2014-09-21 15:08:27,829 INFO: errors [in C:\Users\John\Dropbox\independent_work\groupbot\groupbot\__init__.py:40]
